#!/bin/bash

# Defaut editor
export EDITOR=/usr/local/bin/nvim;

# Oh-My-Zsh installation
export ZSH=$HOME/.oh-my-zsh

# Hide some commands from history
export HISTIGNORE=" *:ls:cd:cd -:pwd:exit:date:* --help:* -h";

# For correct tmux coloring
export TERM=xterm-256color

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vi'
fi

# Homebrew sbin
export PATH="/usr/local/sbin:$PATH"

# Work with GPG
export GPG_TTY=$(tty)
