# Load aliases
[[ -f $HOME/.aliases ]] && source $HOME/.aliases

# Load exports 
[[ -f $HOME/.exports ]] && source $HOME/.exports

# Load functions
for func in $(ls $HOME/.functions); do
		source "$func"
done

# Manage plugins and themes with antigen
source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions
antigen theme reobin/typewritten
antigen apply 
